'use strict';

module.exports = {
  VISITED_FILL_STYLE: "black",
  VISITED_OUTLINE_STYLE: "red",

  TO_BE_VISITED_FILL_STYLE: "green",
  TO_BE_VISITED_OUTLINE_STYLE: "blue",

  NORMAL_STROKE_STYLE: "black",
  NORMAL_FILL_STYLE: "blue",
  EDGE_STROKE_STYLE: "red",
  EDGE_WEIGHT_FILL_STYLE: "blue",

  ON_PATH_FILL_STYLE: "red",
  ON_PATH_OUTLINE_STYLE: "black",
  START_NODE_FILL_STYLE: "green",
  START_NODE_OUTLINE_STYLE: "black",
  GOAL_NODE_FILL_STYLE: "black",
  GOAL_NODE_OUTLINE_STYLE: "yellow",


  ITERATION_EDGE_COLORING: "blue",

  PROGRESS_BAR_BACKGROUND: "red",
  PROGRESS_BAR_FILLING: "blue",
  PROGRESS_BAR_OUTLINE: "black",

  DISTANCE_FONT_COLOR: "orange",
  LEVEL_FONT_COLOR: "orange",

  DEFAULT_FONT: "bold 20px Arial",

  LINE_WIDTH: 5,
  ARROW_LENGTH: 10,

  DEFAULT_NODE_RADIUS: 30,
  NODE_SPEED: 20
};
